name: Continuous Delivery
on:
  push:
    branches:
      - main # qualquer branch

jobs:
  deliver:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Simulação Continuous Delivery
        uses: actions/upload-artifact@v4
        with:

          name: zipado.zip

          path: |
            **.py
            README.md

deploy:
    runs-on: windows-latest

    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Arquivotest.zip
          
      - name: Display dowload files
        run: ls -r
      