name: Continuos Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

  test-job:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Executar análise de segurança estática
        uses: AppThreat/sast-scan-action@master
        with:
          target: index.html, script.js, style.css
          report_type: summary
          severities: high, medium
        env:
          RISK_LEVEL: '10'
      
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint