name: Continuous Delivery
on:
  push:
    branches:
      - main # qualquer branch

jobs:
  deliver:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Simulação Continuous Delivery
        uses: actions/upload-artifact@v4
        with:

          name: zipado.zip

          path: |
            **.py
            README.md
